@startuml Cache
namespace leveldb {
    interface Cache {
        + Cache()
        + ~Cache()
        + Insert(key: Slice, value: void*, charge: size_t, deleter: void(*)(Slice, void*)) : Handle*
        + Lookup(key: Slice) : Handle*
        + Release(handle: Handle*)
        + Value(handle: Handle*) : void*
        + Erase(key: Slice)
        + NewId() : uint64_t
        + Prune()
        + TotalCharge() : size_t
    }

    Cache::Handle

    class NewLRUCache {
        + NewLRUCache(capacity: size_t) : Cache*
    }

    Cache <|.. NewLRUCache
}
@enduml
