@startuml MemTable

' 定义 MemTable 包结构
package "MemTable 系统" {
    [MemTable] --> [SkipList]
    [MemTable] --> [Arena]
    [SkipList] --> [Entry]
    [Entry] --> [Arena]
    [SkipList] --> [KeyComparator]

    package "Entry" {
        package "LookupKey"{
            rectangle "key_size" {
                note bottom: varint32 编码的键长度
            }
            package "internal_key"{
                package "user_key"{
                    rectangle "key_bytes" {
                        note bottom: char[key_size] 实际键内容
                    }
                }
                rectangle "tag" {
                    note bottom: unit64_t 序列号（64 位）<<8 | 类型 (8 位)
                }
            }
        }
        rectangle "value_size" {
            note bottom: varint32 编码的值长度
        }
        rectangle "value_bytes" {
            note bottom:char[value_size] 实际值内容
        }
    }

}

' 定义 Env 节点
cloud "SkipList" {
}


@enduml
